import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "2.1.20"
    id("com.gradleup.shadow") version "9.3.0"
}

group = "me.udnek"
version = "1.0-SNAPSHOT"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

repositories {
    mavenCentral()
    maven { url = uri("https://repo.papermc.io/repository/maven-public/") }

    maven { url = uri("https://oss.sonatype.org/content/groups/public/") }

    maven { url = uri("https://repo.maven.apache.org/maven2/") }
}

dependencies {
    compileOnly(files("C:/Users/PC/IdeaProjects/CoreU/build/libs/CoreU-1.0-SNAPSHOT.jar"))
    compileOnly(files("C:/Users/PC/IdeaProjects/RpgU/build/libs/RpgU-1.0-SNAPSHOT.jar"))
    compileOnly("io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT") {
        exclude(group = "org.apache.commons", module = "commons-lang3")
    }
    compileOnly("org.apache.commons:commons-lang3:3.20.0")

    implementation(kotlin("stdlib-jdk8"))
}


tasks {
    compileKotlin {
        compilerOptions.jvmTarget.set(JvmTarget.JVM_21)
    }
    compileJava {
        options.release.set(21)
    }
    shadowJar {
        archiveBaseName.set("ToughAsNailsU")
        archiveClassifier.set("")
        archiveVersion.set(version.toString())
    }
}


